baseURL = "https://aishpant.github.io/"
languageCode = "en-us"
title = "Aishwarya Pant"
theme = "minimo"

contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = false
googleAnalytics = "UA-111558627-1"

Paginate = 7

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Outreachy intern with Linux Kernel | Flipkart | IIITDelhi | Becoming human | Pant wearer | Currently reading 📖"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "Jan 02, 2006"
listDateFormat = "Jan 02, 2006"
hideEntryNavigation = ["page"] # boolean / array of sections
recentPostsLength = 5
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "aishpant@gmail.com"
facebook = "pantaish"
github = "aishpant"
instagram = "aishpant"
twitter = "aishpant"

[params.social.config]
platforms = ["github","facebook","twitter","instagram","email"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
